Category:
  fields:
    list: title, position
    form: title, show_answers, show_gallery, content
  order_by: position
  search: title
  application: Категории
  description: Категории страниц, главные страницы (главные пункты меню). Могут содержать одну либо несколько страниц. Если страница только одна, она показывается при клике на категорию, если их несколько, показывается список
  relationships: pages
Page:
  fields:
    list: title, image_file_name, category
    form: title, content, category, image_file_name
    options:
      tiny_mce:
        fields: content
  application: Страницы
  description: Все страницы сайта. Содержатся в категориях. Если добавляете в одну категорию несколько страниц не забудьте добавить списочные картинки к каждой странице
  relationships: images
Answer:
  fields:
    list: title 
    form: title, content
    options:
      tiny_mce:
        fields: content
  application: Содержимое блока "А знаете ли вы ?" 
  description: Блок "А знаете ли Вы" - два случайных текста которые выбираются из данного раздела
Image:
  fields:
    list: image_file_name
    form: page, image_file_name
  application: Галерея
  description: Галерея сайта (блок из трех случайных картинок, можно подключать для любой категории)
